name: torch
channels:
  - anaconda
  - plotly
  - programfan
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - certifi=2021.5.30
  - colorama=0.4.5
  - dataclasses=0.8
  - ffmpeg=4.3
  - fortran-language-server=1.12.0
  - freetype=2.11.0
  - future=0.18.2
  - fypp=3.1
  - gettext=0.21.0
  - gmp=6.2.1
  - gnutls=3.6.15
  - icu=58.2
  - intel-openmp=2022.0.0
  - jpeg=9d
  - lame=3.100
  - lcms2=2.12
  - libcxx=12.0.0
  - libffi=3.3
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.37
  - libprotobuf=3.18.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - libxml2=2.9.12
  - llvm-openmp=12.0.0
  - lz4-c=1.9.3
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ncurses=6.3
  - nettle=3.7.3
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - onnx=1.10.1
  - onnxruntime=1.9.0
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1q
  - pandas=1.1.5
  - pillow=8.3.1
  - pip=21.2.2
  - plotly=5.10.0
  - python=3.6.13
  - python-dateutil=2.8.2
  - python-flatbuffers=2.0
  - python_abi=3.6
  - pytorch=1.10.2
  - pytorch-model-summary=0.1.1
  - re2=2021.09.01
  - readline=8.1.2
  - setuptools=58.0.4
  - six=1.15.0
  - sqlite=3.37.0
  - tenacity=8.0.1
  - tk=8.6.11
  - torchvision=0.11.3
  - tqdm=4.64.0
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==0.15.0
    - anyio==3.6.1
    - appnope==0.1.3
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - astunparse==1.6.3
    - async-generator==1.10
    - attrs==21.4.0
    - babel==2.10.3
    - backcall==0.2.0
    - bleach==4.1.0
    - cached-property==1.5.2
    - cachetools==4.2.4
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - clang==5.0
    - contextvars==2.4
    - decorator==5.1.1
    - defusedxml==0.7.1
    - entrypoints==0.4
    - flatbuffers==1.12
    - gast==0.4.0
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.44.0
    - h5py==3.1.0
    - idna==3.3
    - immutables==0.18
    - importlib-metadata==4.8.3
    - ipykernel==5.5.6
    - ipython==7.16.3
    - ipython-genutils==0.2.0
    - jedi==0.17.2
    - jinja2==3.0.3
    - json5==0.9.8
    - jsonschema==3.2.0
    - jupyter-client==7.1.2
    - jupyter-core==4.9.2
    - jupyter-server==1.13.1
    - jupyterlab==3.2.9
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.10.3
    - keras==2.6.0
    - keras-preprocessing==1.1.2
    - markdown==3.3.6
    - markupsafe==2.0.1
    - mistune==0.8.4
    - nbclassic==0.3.5
    - nbclient==0.5.9
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.5
    - notebook==6.4.10
    - oauthlib==3.2.0
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandocfilters==1.5.0
    - parso==0.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.29
    - protobuf==3.19.4
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pygments==2.11.2
    - pyparsing==3.0.9
    - pyrsistent==0.18.0
    - pytz==2022.1
    - pyzmq==22.3.0
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - send2trash==1.8.0
    - sniffio==1.2.0
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.6.2
    - tensorflow-estimator==2.6.0
    - tensorflow-hub==0.12.0
    - termcolor==1.1.0
    - terminado==0.12.1
    - testpath==0.6.0
    - tornado==6.1
    - traitlets==4.3.3
    - urllib3==1.26.8
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.3.1
    - werkzeug==2.0.3
    - wrapt==1.12.1
    - zipp==3.6.0
prefix: /Users/ajaybati/opt/anaconda3/envs/torch
